---

- name: Downloading tmux conf
  git:
    repo: https://github.com/gpakosz/.tmux.git
    dest: "{{ ansible_user_dir }}/.tmux"

- name: Downloading Dots
  unarchive:
    src: https://github.com/killua99/dots/archive/master.zip
    dest: "{{ ansible_user_dir }}"
    remote_src: yes

- name: Linking tmux conf
  file:
    force: yes
    state: link
    src: "{{ ansible_user_dir }}/.tmux/.tmux.conf"
    dest: "{{ ansible_user_dir }}/.tmux.conf"

- name: Move dots folder
  command:
    chdir: "{{ ansible_user_dir }}"
    cmd: mv dots-master dots

- name: Installing dots
  command:
    chdir: "{{ ansible_user_dir }}/dots"
    cmd: "./install.sh"
