- name: Downloading Dots
  unarchive:
    src: https://github.com/killua99/dots/archive/master.zip
    dest: "{{ ansible_user_dir }}/dots"
    remote_src: yes

- name: Installing dots
  command:
    chdir: "{{ ansible_user_dir }}/dots"
    cmd: "./install.sh"
